name: Pangolin
description: A Desktop Environment Written in Flutter.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">= 2.0.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  intl:
  expressions: ^0.2.1
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  flutter_colorpicker: ^0.4.0
  google_fonts: ^2.0.0
  path: ^1.7.0
  process_run: ^0.12.1
  open_file:
  filesize: #missing migration
  xdg_directories: ^0.2.0
  animations:
  recase: ^4.0.0-nullsafety.0
  easy_localization: ^3.0.0
  xml: ^5.0.2
#Useful in an ideal future but not now.  random_color: ^1.0.5

dev_dependencies:
  mockito: ^5.0.3
  json_serializable: ^4.1.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
# application.json handles all applications and must not be deleted.
flutter:
  uses-material-design: true
  fonts:
    - family: Sulphur Point
      fonts:
        - asset: fonts/SulphurPoint/SulphurPoint-Bold.ttf
        - asset: fonts/SulphurPoint/SulphurPoint-Light.ttf
        - asset: fonts/Cousine/Cousine-Italic.ttf
        - asset: fonts/SulphurPoint/SulphurPoint-Regular.ttf
    - family: Cousine
      fonts:
        - asset: fonts/Cousine/Cousine-Bold.ttf
        - asset: fonts/Cousine/Cousine-BoldItalic.ttf
        - asset: fonts/Cousine/Cousine-Italic.ttf
        - asset: fonts/Cousine/Cousine-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Source Code pro
      fonts:
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLight.ttf
          weight: 100
        - asset: fonts/Source_Code_Pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/Source_Code_Pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: fonts/Source_Code_Pro/SourceCodePro-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/Source_Code_Pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBold.ttf
          weight: 700
        - asset: fonts/Source_Code_Pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Bold.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Source_Code_Pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/Source_Code_Pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic
  assets:
    - assets/images/
    - assets/images/credits/profiles/
    - assets/images/wallpapers/dahliaOS/
    - assets/images/wallpapers/Nature/
    - assets/images/icons/PNG/
    - assets/images/logos/dahliaOS/PNG/
    - assets/locales/
